# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libcgal-dev libglu1-mesa-dev mesa-common-dev; fi

addons:
       apt:
         update: true
         sources:
           - sourceline: 'ppa:opencpu/imagemagick'
         packages:
           - libmagick++-dev

after_success:
  - Rscript -e 'covr::codecov()'